# Generated by Django 5.0.4 on 2025-02-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Client', 'Client'), ('Nanny', 'Nanny')], max_length=30, null=True),
        ),
    ]
