# Generated by Django 5.0.4 on 2025-02-13 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_nannyprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NannyProfile',
        ),
    ]
