# Generated by Django 5.0.4 on 2025-02-18 09:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_jobapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HireApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(help_text='The title of the job the client is offering', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the job')),
                ('expected_start_date', models.DateField(help_text='Expected date for the nanny to start the job')),
                ('expected_end_date', models.DateField(help_text='Expected date for the nanny to finish the job')),
                ('expected_salary', models.DecimalField(decimal_places=2, help_text='Expected salary for the nanny', max_digits=10)),
                ('work_schedule', models.TextField(help_text='Detailed work schedule for the nanny')),
                ('additional_requirements', models.TextField(blank=True, help_text='Any additional requirements or comments from the client', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', help_text='The current status of the application', max_length=50)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The time the nanny was applied to')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The time the application was last updated')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'Client'}, on_delete=django.db.models.deletion.CASCADE, related_name='hire_applications', to=settings.AUTH_USER_MODEL)),
                ('job_posting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hire_applications', to='base.jobposting')),
                ('nanny', models.ForeignKey(limit_choices_to={'role': 'Nanny'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hire Application',
                'verbose_name_plural': 'Hire Applications',
                'unique_together': {('client', 'nanny', 'job_posting')},
            },
        ),
    ]
