# Generated by Django 5.0.4 on 2025-02-19 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_hireapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, help_text='Name of the company hiring the nanny', max_length=255, null=True)),
                ('company_description', models.TextField(blank=True, help_text='Brief description of the company', null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Profile',
                'verbose_name_plural': 'Client Profiles',
            },
        ),
        migrations.CreateModel(
            name='NannyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('biography', models.TextField(blank=True, help_text='Brief biography of the nanny', null=True)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('certifications', models.TextField(blank=True, help_text='Certifications or courses completed', null=True)),
                ('languages_spoken', models.TextField(blank=True, help_text='Languages spoken by the nanny', null=True)),
                ('previous_employers', models.TextField(blank=True, help_text='Details of previous employers', null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate for services', max_digits=10, null=True)),
                ('preferred_working_hours', models.TextField(blank=True, help_text='Preferred working hours', null=True)),
                ('availability_notes', models.TextField(blank=True, help_text='Any additional availability notes', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nanny_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nanny Profile',
                'verbose_name_plural': 'Nanny Profiles',
            },
        ),
    ]
