# Generated by Django 5.0.4 on 2025-02-13 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_nannyprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_children', models.IntegerField(default=1, help_text='Number of children')),
                ('special_requirements', models.TextField(blank=True, help_text='Any special needs or requirements', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to='base.userprofile')),
            ],
        ),
    ]
