# Generated by Django 5.0.4 on 2025-03-12 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_team_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='slug',
        ),
    ]
